### ISSUE TITLE
Cannot export

### ISSUE THREAD

**Issue by Christian0112** [jerryliuoft/SilenceRemover#2]
Hi!
This tool seems amazing. But I also cannot export my videos. I tries both Firefox and Chrom on Mac. The error message I get is:

FFMPEG_END

My file is 101 MB big. 

Thank you!
Christian

**Comment by Christian0112** [comment]
I'd be fantastic if this could be fixed. It would make a huge difference if I could use your program to edit the lectures I record for my classes.

**Comment by Christian0112** [comment]
Hi Jerry!

Thank's so much for your answer. It still doesn't work. Just to be sure: I should be able to download the edited mp4 file? Not just an xml file (which I can download but don't know what to do with)?

If I look into console, as you described, the red part say:

index-0e8b7cc3.js:128 Uncaught (in promise) Error: ffmpeg.FS('readFile', 'out.mp4') error. Check if the path exists
    at Object.I [as FS] (index-0e8b7cc3.js:128:4996)
    at HTMLButtonElement.v [as $$click] (index-0e8b7cc3.js:243:2863)


Thank you for any help you might be able to provide!
Christian

**Comment by jerryliuoft** [comment]
The previous person was also having this problem! Yea you can just download the video, the xml is for video editing software like davinci resolve or premier.

I did a quick search, and I think this is due to the cuts. If you remove all the cutting zones, and just have 1 zone left, if my hypothesis is right, then that should work.

then you might want to do some trial and error and see which particular cuts don't work. or it might be there are too many zones? I've yet to figure out if there's a maximum

**Comment by jerryliuoft** [comment]
this should be fixed on the latest version
