### ISSUE TITLE
WAV files XML contains NaN

### ISSUE THREAD

**Issue by miguelhhtc** [jerryliuoft/SilenceRemover#8]
For reference
![image](https://github.com/jerryliuoft/SilenceRemover/assets/63260837/d91b98f8-be6b-4dc2-81e6-4e2a37d483ca)

**Comment by jerryliuoft** [comment]
Hey thanks for the screenshot, this really helps!
The basic problem is that wav file don't have videos, and so my application don't know what to do with it.

Its bit difficult for me to support just audio at this point because the UI will have to change. But if you just need an audio version of this I think there are quiet alot out there (since the tech is simpler). I heard https://www.reaper.fm/ is one of them
